### ISSUE TITLE
Not enough room for balance

### ISSUE THREAD

**Issue by simonredfern** [OpenBankProject/Social-Finance#24]
See the following image.

<img width="275" alt="currency too small" src="https://cloud.githubusercontent.com/assets/485218/13905754/bac55a8e-eec0-11e5-9cd9-4244dddba7e2.png">

**Comment by sebtesobe** [comment]
I have deployed a fix so https://sofisandbox.openbankproject.com . Can you please test there or give me the URL you were using to make that screenshot?
